### ISSUE TITLE
Illustrator crashes when Optical size < Font size

### ISSUE THREAD

**Issue by ThreeSevenths** [TypeNetwork/Roboto-Extremo#381]
Hello, I installed the latest version available this morning of Roboto-Flex on a Windows 11 PC. In Illustrator CC, if I am adjusting the variables, and adjust the optical size to be less than the point size of the font, Illustrator crashes. I have not experienced this particular issue with other variable fonts (Recursive, Source Sans Variable, etc)

[roboto-flex-issue.zip](https://github.com/googlefonts/roboto-flex/files/11918460/roboto-flex-issue.zip)

**Comment by seangoogoo** [comment]
Same for me with Illustrator 28.1 on Apple M2 Pro / Sonoma 14.4.1
Illustrator Crashes each time I try to use Roboto Flex > Medium.

**Comment by kenmcd** [comment]
Have you asked Adobe about this issue?

**Comment by seangoogoo** [comment]
To whom? Adobe?

**Comment by ThreeSevenths** [comment]
I did try contacting Adobe support. It went about as well as expected, and as well as this issue.

**Comment by FreakyPenguin** [comment]
Tagging on here too, as my wife is also currently struggling with OS X illustrator crashes with Roboto Flex (even when not fiddling with settings for the font).

**Comment by kenmcd** [comment]
I have a wild guess I am going to try to test locally.
In a Sonoma 14.4.1 VM. Have to install IL first.
Does it do the same thing in InDesign? 
(think I already have that installed)
This guess is not based on an issue with the font (it is fine).
This guess is based on an issue in IL/Adobe.
I am going to change one thing in the font and see if it works.
(using doc above).
Note: This is a WAG (wild ass guess).
Do not get your hopes up.
If this does not work, you really need to get the answer from Adobe.
If it does work, it is because Adobe is doing non-standard stuff, and again, you really need to get the answer from Adobe.
Nothing "wrong" with the font as is.

**Comment by davelab6** [comment]
Sorry to hear about these Illustrator bugs, everyone. I guess @kenmcd has it right - I believe the font is well-formed technically and this is an Adobe bug. Therefore I'm closing this issue, but I'll send folks I know at Adobe a note about it.

**Comment by josh-hadley** [comment]
Just noting here for the record that I have opened an Adobe-internal ticket with the Illustrator team about this. I can't force or guarantee any action on it, but the fact that it's a crasher should accelerate them looking into it.

**Comment by josh-hadley** [comment]
Hi folks — this seems to no longer be an issue with the latest Illustrator (29.5.1) and the current Roboto Flex downloaded from Google Fonts today so the Illustrator team is planning to close out the aforementioned internal ticket about this bug. If anyone is still having problems with the latest Illustrator and the latest Roboto Flex, please comment here (and ideally provide detailed steps to repro).

**Comment by m4rc1e** [comment]
Thanks for the update Josh! Fantastic news.

**Comment by ThreeSevenths** [comment]
A quick and simple test confirms it appears to be working as you described. Thank you for following up with the community!

**Comment by josh-hadley** [comment]
Great 😸 Sorry it has taken over a year to get here, but the gears sometimes turn slowly.
